ignore:
  # generator is a supporting utility built for humans; it isn't an integral
  # part of Gnomock
  - cmd/generator/**/*
  - internal/testutil/**/*

coverage:
  status:
    project:
      target: 80%
      threshold: 0%
    patch:
      target: 70%
      threshold: 0%
