version: '3'

tasks:
  #
  # Tests
  #

  test:core:gnomock:
    env:
      GOMAXPROCS: 2
    cmds:
      - go test -race -cover -coverprofile=gnomock-cover.txt -coverpkg=./... -v .

  test:core:gnomockd:
    env:
      GOMAXPROCS: 2
    cmds:
      - go test -race -cover -coverprofile=gnomockd-cover.txt -coverpkg=./... -v ./internal/gnomockd -run TestGnomockd

  test:core:internal:
    env:
      GOMAXPROCS: 2
    cmds:
      - |
        go test -race -cover -coverprofile=internal-cover.txt -v -coverpkg=./... \
          ./internal/errors \
          ./internal/registry \
          ./internal/cleaner \
          ./internal/health

  #
  # SDK release routines
  #

  release:sdk:python:
    cmds:
      - task: swagger:update-version
      - task: git:clone:python
      - task: generate:sdk:python
      # - task: test:sdk:python
      - task: git:commit:python
      - rm -rf ./dist
      - deactivate || true
      - python3 setup.py sdist bdist_wheel
      - python3 -m twine upload dist/*
    dir: ./sdktest/python/gnomock

  swagger:update-version:
    cmds:
      - |
        sed -Ei '' 's/^  version: (.*)$/  version: {{.version}}/' swagger/swagger.yaml
      - |
        sed -Ei '' 's/^packageVersion: (.*)$/packageVersion: {{.version}}/' swagger/config/python.yaml
      - |
        sed -Ei '' 's/apis\/orlangure\/gnomock\/(.*)#/apis\/orlangure\/gnomock\/{{.version}}#/' README.md
      - git add README.md swagger/config/python.yaml swagger/swagger.yaml
      - git commit -m 'Update version to {{.version}}'
    silent: true
    dir: .
    vars:
      CURRENT_BRANCH:
        sh: git branch --show-current
    preconditions:
      - sh: test $version
        msg: version is not set
      - sh: test "{{.CURRENT_BRANCH}}" != "master"
        msg: version changes cannot happen on master branch

  git:clone:python:
    cmds:
      - rm -rf gnomock
      - git clone --depth 1 https://github.com/orlangure/gnomock-python-sdk gnomock
    dir: ./sdktest/python

  generate:sdk:python:
    cmds:
      - |
        docker run --rm -v $PWD:/local \
          openapitools/openapi-generator-cli:v4.3.1 generate \
          -i /local/swagger/swagger.yaml \
          -g python \
          -o /local/sdktest/python/gnomock \
          -c /local/swagger/config/python.yaml \
          --git-user-id orlangure \
          --git-repo-id gnomock-python-sdk
    silent: true
    dir: .

  git:commit:python:
    cmds:
      - rm .travis.yml
      - git add .
      - git commit -m 'Bump version to {{.version}}'
      - git push
    dir: ./sdktest/python/gnomock
    preconditions:
      - sh: test $version
        msg: version is not set

  test:sdk:python:
    cmds:
      - task: gnomock:run
      - |
        {{ if not .CI }}
        python3 -m venv venv
        source venv/bin/activate
        {{ else }}
        docker system df
        docker system prune -f
        docker system df
        {{ end }}
        pip3 install -r requirements.txt
        python3 -m pytest -n 1 -v -k TestSDK
      - task: gnomock:stop
    dir: ./sdktest/python

  gnomock:run:
    cmds:
      - task: gnomock:stop
      - task: gnomock:build:server
      - task: gnomock:build:cleaner
      - |
        docker run -itd --rm \
        -p 23042:23042 \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $PWD:$PWD \
        --name gnomockd_test \
        orlangure/gnomock
    dir: .

  gnomock:stop:
    cmds:
      - docker container stop gnomockd_test || true

  gnomock:build:server:
    env:
      DOCKER_BUILDKIT: "1"
    cmds:
      - docker build --progress plain --tag orlangure/gnomock .
    dir: .

  gnomock:build:cleaner:
    env:
      DOCKER_BUILDKIT: "1"
    cmds:
      - docker build --progress plain --tag orlangure/gnomock-cleaner .
    dir: ./cmd/cleaner

  gnomock:upload:cleaner:
    vars:
      CURRENT_BRANCH:
        sh: git branch --show-current
    cmds:
      - task: gnomock:build:cleaner
      - docker push orlangure/gnomock-cleaner
      - docker tag orlangure/gnomock-cleaner orlangure/gnomock-cleaner:{{.version}}
      - docker push orlangure/gnomock-cleaner:{{.version}}
    preconditions:
      - sh: test $version
        msg: version is not set
      - sh: test "{{.CURRENT_BRANCH}}" == "master"
        msg: docker images must be built on master

  gnomock:upload:server:
    vars:
      CURRENT_BRANCH:
        sh: git branch --show-current
    cmds:
      - task: gnomock:build:server
      - docker push orlangure/gnomock
      - docker tag orlangure/gnomock orlangure/gnomock:{{.version}}
      - docker push orlangure/gnomock:{{.version}}
    preconditions:
      - sh: test $version
        msg: version is not set
      - sh: test "{{.CURRENT_BRANCH}}" == "master"
        msg: docker images must be built on master

  release:gnomock:docker:
    cmds:
      - task: gnomock:upload:cleaner
      - task: gnomock:upload:server
